# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
    Thanks for opening your first issue! Reports like these help improve the project!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
    Thanks for opening this pull request! 

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
    Congrats on merging your first pull request!

# The keyword to find for Todo Bot issue
todo:
    keyword: '@todo'



# You can search for repositories using GitHub's repo search syntax
# https://help.github.com/en/github/searching-for-information-on-github/searching-for-repositories
repoSearch: org:REVREBEL language:typescript language:javascript is:public archived:false

# Alternatively, you can specify repositories explicitly like this:
# repos:
#   - org: REVREBEL
#     regex: nodejs-.*
#   - org: REVREBEL
#     name: github-repo-automation
