name: Issue Close (Needs Reproduction)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  metadata: read

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale 'needs reproduction' issues
        uses: actions-cool/issues-helper@0a220d0ec9d2711f3a181d7e332be32013e68ac8
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: status: needs reproduction
          inactive-day: 7
          close-reason: not_planned
